name: ga4_ecommerce_analytics
version: '1.0.0'
config-version: 2

profile: ga4_ecommerce_dbt

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  ga4_ecommerce_analytics:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table

vars:
  dev_start_date: "2020-11-27"
  dev_end_date: "2020-11-30"